### 1. Neogene gtf -------------------------------------------------------------
# For this gtf, I'm using the hg38 gtf generated by Luuk containing both the neogenes and neoisoforms
#However, the neoisoforms in the merge with Princess Maxima were not always assigned to neoisoforms but sometimes to neogenes.

# Load libraries
library(rtracklayer)
library(GenomicRanges)
library(dplyr)
library(readxl)

# Load merged gtf with all isoforms and neogenes
gtf <- import(".../20260408_EwS_neotranscripts_combined_orfs.gtf")

# Convert to a dataframe
df = as.data.frame(gtf)
table(df$neotranscript_type)

# Create the neogene gtf 
df_neo = df %>%
  filter(neotranscript_type=="Neogene")

unique(df_neo$gene_name)
unique(df_neo$gene_id)
unique(df_neo$neogene_id)

gtf.neogenes = makeGRangesFromDataFrame(df_neo, keep.extra.columns=TRUE,
                                     seqinfo=NULL)

rtracklayer::export(gtf.neogenes, ".../20260409_124_neogenes_Curie_PMC.gtf")

### 2. Neoisoforms gtf ---------------------------------------------------------
df <- readxl::read_xlsx(".../neoisoforms_ORFs_with_dups_collasped.xlsx")
old_hg38 <- import(".../neotranscripts_all_hg38_20250318.gtf")

isoforms_to_keep <- unique(df$isoform_version)
gtf_filtered <- old_hg38[mcols(old_hg38)$transcript_id %in% isoforms_to_keep]
gtf_df <- as.data.frame(gtf_filtered)

cols_to_drop <- c(
  "isoform_type",
  "XLOC_id",
  "gffcompare_Ensembl_gene_id",
  "gffcompare_Ensembl_transcript_id",
  "gff_compare_sqanti_Ensembl_transcript_id",
  "membrane_annot",
  "Gene_gff_compare_old_annot",
  "oId",
  "cmp_ref",
  "class_code",
  "tss_id",
  "num_samples",
  "contained_in",
  "cmp_ref_gene",
  "exon",
  "ID",
  "RPKM",
  "cov"
)

gtf_df <- gtf_df[, !(colnames(gtf_df) %in% cols_to_drop)]

df_sub <- df[, c(
  "isoform_version",
  "isoform_final",
  "isoform_final_subtype",
  "neotranscript_orf_type_per_isoform",
  "known_orf_id",
  "ORF_ranges"
)]

gtf_annot <- merge(
  gtf_df,
  df_sub,
  by.x = "transcript_id",
  by.y = "isoform_version",
  all.x = TRUE
)

length(unique(gtf_annot$gene_name))
length(unique(gtf_annot$transcript_id))

gtf_final <- makeGRangesFromDataFrame(
  gtf_annot,
  keep.extra.columns = TRUE
)

#  Export GTF hg38
rtracklayer::export(gtf_final, ".../20260415_neoisoforms_hg38.gtf")

### 3. Look at gtf -------------------------------------------------------------
# Load merged gtf with all isoforms and neogenes
gtf <- import(".../20260409_124_neogenes_Curie_PMC.gtf")
gtf = as.data.frame(gtf)
length(unique(gtf$neogene_id))
colnames(gtf)


# Load merged gtf with all isoforms and neogenes
gtf <- import(".../20260415_neoisoforms_hg38.gtf")
gtf = as.data.frame(gtf)
colnames(gtf)
