# The goal of this script is to compare KASH5 ORFs with other cancer testis antigen translation levels

# Libraries, functions and paths -----------------------------------------------
library(ggplot2)
library(devtools)
library(tidyr)
library(dplyr)
library(readxl)
library(paletteer)
library(rtracklayer)
library(openxlsx)
library(Rgff)
library(GenomicRanges)
library(biomaRt)
httr::set_config(httr::config(ssl_verifypeer = FALSE))
library(ComplexHeatmap)
library(circlize)

data_dir <- ".../Expression_PM/"
`%nin%` <- Negate(`%in%`)

# Load data --------------------------------------------------------------------
Meta_data <- read.csv(paste0(data_dir, "EwS_ribo_meta_all.csv")) %>%
  dplyr::filter(source == "patient_sample") 

# Prepare metadata and expression matrix ---------------------------------------
Meta_data <- Meta_data %>%
  mutate(id = case_when(
    source == "cell_line" ~ paste0("CL_", sample_id),
    source == "patient_sample" ~ paste0("PS_", sample_id)
  ))


# Use the MANE data to get all the genes of interest and not only the ones with detected expression in Riboseq---------
all <- read.csv(paste0(data_dir, "ppm_counts_MANE_all.csv"))

# Keep only samples present in metadata-----------------------------------------
names <- rownames(all)
all <- all[, colnames(all) %in% Meta_data$id]
all <- as.matrix(sapply(all, as.numeric))
rownames(all) <- names

# Get the cancer antigen list from CTexploreR-----------------------------------
CTexploreR <- read.csv(".../CT_genes_latest_CTexploreR.csv")
dim(CTexploreR)

CTexploreR_ids <- CTexploreR$ensembl_gene_id

# Get CTDatabase----------------------------------------------------------------
CTDatabase <- read_xlsx(".../Cancer_testis_genes/CTDatabase.xlsx")
dim(CTDatabase)

# Extract ENSG only for canonical genes-----------------------------------------
CTA_df <- as.data.frame(all)
dim(CTA_df)
rownames(CTA_df)

# Biomart annotation of CTDatabase ---------------------------------------------
Sys.unsetenv("http_proxy")
Sys.unsetenv("https_proxy")
Sys.unsetenv("HTTP_PROXY")
Sys.unsetenv("HTTPS_PROXY")

mart <- useEnsembl("ensembl", dataset = "hsapiens_gene_ensembl")

bm <- getBM(
  attributes = c("external_gene_name", "ensembl_gene_id"),
  filters = "external_gene_name",
  values = CTDatabase$`Family member`,
  mart = mart
)

CTDatabase_annot <- merge(
  CTDatabase,
  bm,
  by.x = "Family member",
  by.y = "external_gene_name",
  all.x = TRUE
) %>%
  distinct(ensembl_gene_id, .keep_all = TRUE)

length(unique(CTDatabase_annot$`Family member`))

# Keep CT genes + ORFs----------------------------------------------------------
CTA_keep <- unique(na.omit(c(
  CTDatabase_annot$ensembl_gene_id,
  CTexploreR_ids
)))

CTA_keep

CTA_df <- CTA_df %>%
  dplyr::filter(rownames(.) %in% CTA_keep)

dim(CTA_df)

CTA_df$ENSG <- rownames(CTA_df)

ensg_ids <- unique(CTA_df$ENSG)

# Query biomaRt to get gene_names ----------------------------------------------
gene_mapping <- getBM(
  attributes = c("ensembl_gene_id", "external_gene_name", "description"),
  filters    = "ensembl_gene_id",
  values     = ensg_ids,
  mart       = mart
)

# Join back to your original table----------------------------------------------
CTA_df <- CTA_df %>%
  left_join(gene_mapping, by = c("ENSG" = "ensembl_gene_id")) %>%
  dplyr::rename(gene_name = external_gene_name)

rownames(CTA_df) <- CTA_df$gene_name

CTA_df = CTA_df %>%
  dplyr::select(!c(ENSG, gene_name, description))


# Convert dataframe to numeric matrix ------------------------------------------
mat <- as.matrix(sapply(CTA_df, as.numeric))
rownames(mat) <- rownames(CTA_df)

# OPTIONAL: log transform if needed --------------------------------------------
# mat <- log2(mat + 1)

# Define ordering BEFORE scaling -----------------------------------------------
row_means <- rowMeans(mat, na.rm = TRUE)

# Order genes from highest to lowest mean expression
ord <- order(row_means, decreasing = TRUE)

# Reorder original matrix
mat <- mat[ord, ]

dim(mat)

# Select top 10 expressed genes BEFORE scaling ---------------------------------
top12_genes <- rownames(mat)[1:12]

# Z-score scaling for visualization only ---------------------------------------
mat_z <- scale(mat)

# Replace NA values generated by zero-variance rows
mat_z[is.na(mat_z)] <- 0

# Define color mapping ---------------------------------------------------------
col_fun <- circlize::colorRamp2(
  c(-2, 0, 2),
  c("blue", "white", "red")
)

# Get row indices AFTER ordering ------------------------------------------------
gene_id <- which(rownames(mat_z) %in% top12_genes)

# Labels
labels <- rownames(mat_z)[gene_id]

# Heatmap ----------------------------------------------------------------------
h <- Heatmap(
  mat_z,
  
  col = col_fun,
  name = "Ribo-seq normalized counts (ppm)",
  
  border_gp = gpar(col = "black", lty = 3),
  
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  
  show_row_names = FALSE,
  show_row_dend = FALSE,
  show_column_names = FALSE,
  
  column_names_gp = gpar(fontsize = 5),
  
  heatmap_legend_param = list(
    title_gp = gpar(
      fontsize = 5,
      fontface = "plain"
    ),
    
    labels_gp = gpar(fontsize = 5),
    
    legend_height = unit(3, "cm"),
    legend_width = unit(4, "cm")
  ),
  
  # Annotated genes ------------------------------------------------------------
  right_annotation = rowAnnotation(
    genes = anno_mark(
      at = gene_id,
      labels = labels,
      
      labels_gp = gpar(
        fontsize = ifelse(labels == "KASH5", 8, 5),
        fontface = ifelse(labels == "KASH5", "bold", "plain"),
        col = ifelse(labels == "KASH5", "red", "black")
      )
    )
  )
)

# Draw heatmap -----------------------------------------------------------------
draw(h)

# Save PDF ---------------------------------------------------------------------
pdf(
  ".../heatmap_Riboseq_ppm_CTA.pdf",
  width = 8,
  height = 3,
  family = "Helvetica"
)

draw(h)
dev.off()
